# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

default_platform(:ios)

platform :ios do
  lane :build do
    app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
    team_id = CredentialsManager::AppfileConfig.try_fetch_value(:team_id)

    setup_ci(force: 'true')
    match(
      app_identifier: [app_identifier, 'de.tum.cit.ase.artemis.ArtemisNotificationExtension'],
      type: 'appstore',
      git_url: ENV['MATCH_GIT_URL'],
      git_basic_authorization: ENV['MATCH_GITLAB_AUTH'],
      api_key: api_key
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      code_sign_identity: "iPhone Distribution",
      sdk: "iphoneos*",
      profile_name: "match AppStore de.tum.cit.ase.artemis",
      bundle_identifier: "de.tum.cit.ase.artemis",
      team_id: team_id
    )
    build_app(
      scheme: "Artemis",
      clean: true,
      xcargs: "-skipMacroValidation -skipPackagePluginValidation",
      export_options: {
        provisioningProfiles: {
          "de.tum.cit.ase.artemis" => "match AppStore de.tum.cit.ase.artemis",
          "de.tum.cit.ase.artemis.ArtemisNotificationExtension" => "match AppStore de.tum.cit.ase.artemis.ArtemisNotificationExtension"
        }
      }
    )
  end

  lane :api_key do
    app_store_connect_api_key(
      duration: 300, # This Token is valid for 300s
      key_id: ENV['API_KEY_ID'],
      issuer_id: ENV['API_KEY_ISSUER_ID'],
      key_content: ENV['API_KEY_PASSWORD'],
      is_key_content_base64: true
    )
  end
end